### ISSUE TITLE
NPE onLevelCalculated

### ISSUE THREAD

**Issue by bnjrKemal** [weaves7/IslandRankup#2]
```
[19:04:52] [Server thread/INFO]: Mandalina issued server command: /is level
[19:04:54] [Server thread/WARN]: [BentoBox] Task #12003 for BentoBox v1.13.1 generated an exception
java.lang.NullPointerException: group
	at java.util.Objects.requireNonNull(Objects.java:228) ~[?:1.8.0_252]
	at me.lucko.luckperms.bukkit.vault.AbstractVaultPermission.playerAddGroup(AbstractVaultPermission.java:302) ~[?:?]
	at org.makershaven.islandrankup.LevelCalculatedListener.lambda$onLevelCalculated$0(LevelCalculatedListener.java:51) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-372]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.15.2.jar:git-Paper-372]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1264) ~[patched_1.15.2.jar:git-Paper-372]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-372]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181) ~[patched_1.15.2.jar:git-Paper-372]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Paper-372]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```
Merhabalar, eklentinizden memnun oldum. Fakat bu hatanın yüzünden oyuncular ``/is level`` kullandıklarında sonraki rütbe atlayamıyorlar. Çözüme ihtiyacım var.

Sürümler;
```
[00:13:08 INFO]: This server is running Paper version git-Paper-372 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[00:13:08 INFO]: Checking version, please wait...
[00:13:09 INFO]: Previous version: git-Paper-367 (MC: 1.15.2)
[00:13:09 INFO]: You are 3 version(s) behind

[00:13:11 INFO]: BentoBox version 1.13.1
[00:13:11 INFO]: Highly scalable and customizable Minecraft Spigot plugin that enables you to run island-type gamemodes.
[00:13:11 INFO]: Website: https://bentobox.world
[00:13:11 INFO]: Authors: tastybento and Poslovitch

[00:14:39 INFO]: LuckPerms version 5.0.72
[00:14:39 INFO]: A permissions plugin
[00:14:39 INFO]: Website: https://luckperms.net
[00:14:39 INFO]: Author: Luck

[00:14:41 INFO]: Vault version 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
[00:14:41 INFO]: Vault is a Permissions & Economy API to allow plugins to more easily hook into these systems without needing to hook each individual system themselves.
[00:14:41 INFO]: Website: https://dev.bukkit.org/projects/vault
[00:14:41 INFO]: Authors: cereal, Sleaker and mung3r
```

**Comment by weaves7** [comment]
Can I get a paste of your Island Rankup config and your list of luck perms ranks and the ranks of the player executing the command?

**Comment by bnjrKemal** [comment]
```
# Enable anonymous metrics data? Please do, it helps us stay motivated.
metrics: true

# Sends a level up message to the player or as a broadcast.
level_up:
  enabled: true
  message: '&7[&3Ada Rütbe Sistemi&7] &f<PLAYER>''nin yeni rütbesi &8» &a<RANK>'
  broadcast_mode: true

# Should ranks only apply to the world the player is in?
world_specific: true

# You can change these ranks or add to it if you would like, just make sure you follow the format.
ranks:
  hidrojen:
    start: 300
    end: 699
  karbon:
    start: 700
    end: 1199
  oksijen:
    start: 1200
    end: 1199
  klor:
    start: 1800
    end: 2499
  kalsiyum:
    start: 2500
    end: 4599
  bakır:
    start: 4600
    end: 5499
  brom:
    start: 5500
    end: 7799
  ksenon:
    start: 7800
    end: 9999
  oganesson:
    start: 10000
    end: 99999
```
```
> lp listgroups
[01:00:11 INFO]: [LP] Groups: (name, weight, tracks)
[01:00:12 INFO]: [LP] -  bakır - 0
[01:00:12 INFO]: [LP] -  brom - 0
[01:00:12 INFO]: [LP] -  default - 0
[01:00:12 INFO]: [LP] -  hidrojen - 0
[01:00:12 INFO]: [LP] -  kalsiyum - 0
[01:00:12 INFO]: [LP] -  karbon - 0
[01:00:12 INFO]: [LP] -  klor - 0
[01:00:12 INFO]: [LP] -  ksenon - 0
[01:00:12 INFO]: [LP] -  mvip - 0
[01:00:12 INFO]: [LP] -  mvip+ - 0
[01:00:12 INFO]: [LP] -  oganesson - 0
[01:00:12 INFO]: [LP] -  oksijen - 0
[01:00:12 INFO]: [LP] -  rehber - 0
[01:00:12 INFO]: [LP] -  vip - 0
[01:00:12 INFO]: [LP] -  vip+ - 0
```
> and the ranks of the player executing the command?

how so?

**Comment by weaves7** [comment]
`/lp user <username> info` and also what is their current island level?

**Comment by bnjrKemal** [comment]
I don't have to query with that command because they can't be assigned to rank. I just checked a group's permissions. I didn't add the necessary permissions.

Actually, I think it would be healthier to check the group names listed in the yaml without requiring permission and give the group accordingly.

**Comment by weaves7** [comment]
The permission is used to determine if the player has the rank or not, I would be surprised if it had anything to do with your error. This will likely still be changed in a future release though. The problem that I could find while testing is that your ranks start at island level 300. If a player is below this level or above your max level when it checks the yaml for the correct rank; none would be found. This sends a null value to LP which it does not like. I have fixed that issue in this dev build that you can try if you continue to have problems with that error: https://github.com/weaves7/IslandRankup/releases/tag/v1.8.3

**Comment by bnjrKemal** [comment]
Solved, thanks!
